sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
  - stable
script:
  - npm test
  - npm run zuul
env:
  global:
    - secure: B4HTFja7G5YphidIv2/aCohD6MQ1sVcBLZJBhwKYm7g3HMFTs66WtcHFjQBN71eIMCKeiCOcav4fnf7MILMjokeDA4Iwkge/TDUK8OYNkG37tudDafVgAEthA+AHSXL8R/tb/oXQL0ruoHJMwgXEBCs8zImZMkBxfbceTUU7eqz5KzB0sbsEDZPZjSe46qJYRDM9XrdfVUle6n/G24ZfvIszu+5FkpJlAG9trGeHQzL4SkC1t0puELcNRVfSW58TYuZN85RqpkaB6COQO+8N3dsTskY6NGUvNQCS95Cg2ztW/yXaunk6yGVie7n0YdTy2/X9Sx3WhTcYTe/tuKwkISNQoeQUEmAf50YtUC+VG5xMnZNOF4Tth+OyJCEsjT/4sdqxUdGiVUdSXOqWe2ksYJXogISi4IFfQQMe5NPz4QSCHidK4dSMur4x0llAtJw3bSMSrhwiyOthzMHSXBsOitc1Chgf5bhkh995iiUF7shEfp8Aikrg/V2uqTuLWFsJK1vksLebkkQIr/tueClcpo+8CV5jX76UXzirQmFUpB3yX4B3vi0p/MyoCgMYUW3HIy9yaCWN0PR4drz+fyzgGNzpuU8V/kZMMeDdLCZNSwj9FqEgpmoqPCzZKVpt6El32JbJdBd0ANAmIdy3Z/inbrzzb7kgYu2mvSsx6jyDa6c=
    - secure: p0yu6ovRHE99dlBlT//RgHvCyap26YNDn8IU0+nhkGcrPtymDgxJxYxNV1uEMj3HrwP8kdv0e7AH0STEQiujkCErx6TlhYnM7ZPsYfa1JafPRZ0Dw1kIdVbWBFr+zFVcJIpYSb7aH7/Eq60Q9d5QwYqRz4WH/Lbnye2Sd+GrnzpcqVjOLO79Uu+6Ju3M6mLyNCsiCQf6hBSWUrgjKBgRFJzE1t0YCZnw7nY7v4AzqciNiT1z777ijOGHEeufH5t4EbJJQl0fwhic0yU9DEKcrYuMsdx6MowuoIosvt9CsWfWygHw2joEXXxc8ea0g6ez8My/fkaSVU8GRwZ/TqQlCAoOOFmR6a3m3KjIt2/uL7I1857X2/k56wbqVON6Zro9wCY+IHzOfklh6hNkEJ/pvzn5c7r8Z6ggV+imDCk9//VkfmfjYD/5FbDT7NtAr3R0E60kpo3IdUs1y6P/q39dtOA1aD/uTlGRF6IveAxex00aj1Dm3QxeQIurwbf+ASHUuEwNSi9//+kszBPgsAxRsq04oCKiaGVchshE2t/b0DKwQkdonnJSQPdMO+gUHEB1AHt8t4V4WBuijRQupcdN/h0jQ1VViUu9gSeMRfFPNyCT6JdkQ+bzNHvumH96xDJiHXzTBRzKWFaoxcBE8gPIhWu4qkznUsMA4hRkROAV4BA=
