ui: tape
browsers:
  - name: iphone
    version: 8.0
  - name: iphone
    version: 9.0
  - name: android
    version: latest
  - name: android
    version: 4.4
  - name: chrome
    version: -2..latest
    platform: Linux
  - name: firefox
    version: -2..latest
    platform: Linux
  - name: ie
    version: [10, 11]
  - name: microsoftedge
    version: latest
  - name: safari
    version: '7..latest'
html: distribution/test/integration/index.html
